[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "schedule>=1.2.2",
    "streamlit>=1.42.0",
    "textblob>=0.19.0",
    "twilio>=9.4.4",
]
